-- MySQL Script generated by MySQL Workbench
-- Sun Aug  6 21:17:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommerce_db` ;

-- -----------------------------------------------------
-- Schema ecommerce_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce_db` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce_db` ;

-- -----------------------------------------------------
-- Table `ecommerce_db`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Produto` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(20) NOT NULL,
  `classificaCrianca` TINYINT NULL DEFAULT 0,
  `categoria` ENUM('Eletronico', 'Eletrodomestico', 'Vestimenta', 'Escritorio', 'Informatica', 'Brinquedo', 'Alimento', 'Movel') NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `valor` FLOAT NOT NULL,
  `avaliacao` FLOAT NULL DEFAULT 0,
  `dimensoes` VARCHAR(10) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `dataNascimento` DATE NOT NULL,
  `pNome` VARCHAR(15) NOT NULL,
  `nomeMeio` CHAR(15) NULL,
  `sobrenome` VARCHAR(20) NULL,
  `endereco` VARCHAR(145) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Pagamento` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `tipoPagamento` ENUM('PIX', 'Boleto', 'Credito') NOT NULL,
  PRIMARY KEY (`idPagamento`),
  UNIQUE INDEX `tipoPagamento_UNIQUE` (`tipoPagamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `idPedidoCliente_fk` INT NOT NULL,
  `idPedidoPagamento_fk` INT NOT NULL,
  `PedidoDataHora` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `descricao` VARCHAR(144) NULL,
  `frete` FLOAT NULL,
  `totalPedido` FLOAT NULL COMMENT 'Somatório de todos os produtos pedidos + frete final',
  `statusPedido` ENUM('Em processamento', 'Cancelado', 'Pago', 'Atendido') NULL DEFAULT 'Em processamento',
  `CEPpedido` CHAR(8) NOT NULL COMMENT 'Código de endereçamento postal',
  PRIMARY KEY (`idPedido`, `idPedidoCliente_fk`, `idPedidoPagamento_fk`),
  INDEX `fk_idCliente_pedido_idx` (`idPedidoCliente_fk` ASC) VISIBLE,
  INDEX `fk_idTipo_pagamento_idx` (`idPedidoPagamento_fk` ASC) VISIBLE,
  INDEX `statusPedido_idx` (`statusPedido` ASC) INVISIBLE,
  INDEX `CEPpedido_idx` (`CEPpedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`idPedidoCliente_fk`)
    REFERENCES `ecommerce_db`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_pedido`
    FOREIGN KEY (`idPedidoPagamento_fk`)
    REFERENCES `ecommerce_db`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Item` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Item` (
  `idItemPedido_fk` INT NOT NULL,
  `idItemProduto_fk` INT NOT NULL,
  `quantidade` INT NOT NULL DEFAULT 1,
  `statusProduto` ENUM('Disponível', 'Indisponível') NOT NULL DEFAULT 'Disponível',
  `total` FLOAT NULL COMMENT 'Quantidade x Valor do Produto',
  PRIMARY KEY (`idItemPedido_fk`, `idItemProduto_fk`),
  INDEX `statusProduto_idx` (`statusProduto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_item`
    FOREIGN KEY (`idItemProduto_fk`)
    REFERENCES `ecommerce_db`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_item`
    FOREIGN KEY (`idItemPedido_fk`)
    REFERENCES `ecommerce_db`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Vendedor` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Vendedor` (
  `idVendedor` INT NOT NULL AUTO_INCREMENT,
  `razaoSocial` VARCHAR(145) NOT NULL,
  `nomeFantasia` VARCHAR(45) NULL,
  `localidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idVendedor`),
  UNIQUE INDEX `razaoSocial_UNIQUE` (`razaoSocial` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Localidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Localidade` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Localidade` (
  `idLocalidade` INT NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(30) NOT NULL,
  `CEP` CHAR(8) NOT NULL COMMENT 'Código de endereçamento postal.',
  PRIMARY KEY (`idLocalidade`),
  UNIQUE INDEX `cidade_UNIQUE` (`cidade` ASC) VISIBLE,
  INDEX `CEP_idx` (`CEP` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Fornecedor` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `razaoSocial` VARCHAR(145) NOT NULL,
  `CNPJ` CHAR(15) NOT NULL,
  `contato` CHAR(11) NOT NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Vendedor_Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Vendedor_Produto` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Vendedor_Produto` (
  `idVendedor_fk` INT NOT NULL,
  `idProduto_fk` INT NOT NULL,
  `quantidade` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`idVendedor_fk`, `idProduto_fk`),
  INDEX `fk_produto_idx` (`idProduto_fk` ASC) VISIBLE,
  CONSTRAINT `fk_vendedor`
    FOREIGN KEY (`idVendedor_fk`)
    REFERENCES `ecommerce_db`.`Vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor_produto`
    FOREIGN KEY (`idProduto_fk`)
    REFERENCES `ecommerce_db`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Produto_Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Produto_Estoque` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Produto_Estoque` (
  `idProdutoEstoque_fk` INT NOT NULL,
  `idLocalidadeEstoque_fk` INT NOT NULL,
  `quantidade` INT NOT NULL,
  INDEX `fk_idProduto_idx` (`idProdutoEstoque_fk` ASC) INVISIBLE,
  INDEX `fk_idLocalidade_idx` (`idLocalidadeEstoque_fk` ASC) VISIBLE,
  PRIMARY KEY (`idProdutoEstoque_fk`, `idLocalidadeEstoque_fk`),
  CONSTRAINT `fk_produto_estoque`
    FOREIGN KEY (`idProdutoEstoque_fk`)
    REFERENCES `ecommerce_db`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_localidade_estoque`
    FOREIGN KEY (`idLocalidadeEstoque_fk`)
    REFERENCES `ecommerce_db`.`Localidade` (`idLocalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Fornecedor_Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Fornecedor_Produto` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Fornecedor_Produto` (
  `idFornecedor_fk` INT NOT NULL,
  `idProduto_fk` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idFornecedor_fk`, `idProduto_fk`),
  INDEX `fk_produto_idx` (`idProduto_fk` ASC) VISIBLE,
  CONSTRAINT `fk_fornecedor`
    FOREIGN KEY (`idFornecedor_fk`)
    REFERENCES `ecommerce_db`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto`
    FOREIGN KEY (`idProduto_fk`)
    REFERENCES `ecommerce_db`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Tipo` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Tipo` (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('CPF', 'CNPJ') NOT NULL DEFAULT 'CPF',
  `numero` VARCHAR(15) NOT NULL,
  `idTipoCliente_fk` INT NOT NULL,
  PRIMARY KEY (`idTipo`, `idTipoCliente_fk`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) INVISIBLE,
  UNIQUE INDEX `idClienteTipo_fk_UNIQUE` (`idTipoCliente_fk` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_tipo`
    FOREIGN KEY (`idTipoCliente_fk`)
    REFERENCES `ecommerce_db`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Entrega` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Entrega` (
  `idEntrega` INT NOT NULL AUTO_INCREMENT,
  `idPedido_fk` INT NOT NULL,
  `statusEntrega` ENUM('Preparação', 'Despacho', 'Trânsito', 'Entregue') NULL,
  `codigoRastreio` CHAR(15) NULL,
  PRIMARY KEY (`idEntrega`, `idPedido_fk`),
  UNIQUE INDEX `codRastreio_UNIQUE` (`codigoRastreio` ASC) VISIBLE,
  INDEX `fk_pedido_idx` (`idPedido_fk` ASC) VISIBLE,
  CONSTRAINT `fk_pedido`
    FOREIGN KEY (`idPedido_fk`)
    REFERENCES `ecommerce_db`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
