-- MySQL Script generated by MySQL Workbench
-- Mon Jul 31 21:47:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommerce_db` ;

-- -----------------------------------------------------
-- Schema ecommerce_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce_db` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce_db` ;

-- -----------------------------------------------------
-- Table `ecommerce_db`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Produto` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(10) NOT NULL,
  `classificaCrianca` TINYINT NULL DEFAULT 0,
  `categoria` ENUM('Eletrônico', 'Vestimenta', 'Brinquedos', 'Alimentos', 'Móveis') NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `valor` FLOAT NOT NULL,
  `avaliacao` FLOAT NULL DEFAULT 0,
  `dimensoes` VARCHAR(10) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Pagamento` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `tipoPagamento` ENUM('PIX', 'Boleto', 'Cartão', 'Dois Cartões') NOT NULL,
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Entrega` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Entrega` (
  `idEntrega` INT NOT NULL AUTO_INCREMENT,
  `statusEntrega` ENUM('Em andamento', 'Em processando', 'Enviado', 'Entregue') NOT NULL DEFAULT 'Em processando',
  `codRastreio` CHAR(10) NOT NULL,
  PRIMARY KEY (`idEntrega`),
  UNIQUE INDEX `codRastreio_UNIQUE` (`codRastreio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `dataNascimento` DATE NOT NULL,
  `pNome` VARCHAR(10) NOT NULL,
  `nomeMeio` CHAR(3) NULL,
  `sobrenome` VARCHAR(20) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `idPagamento` INT NOT NULL,
  `idPedidoCliente` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `frete` FLOAT NULL,
  PRIMARY KEY (`idPedido`, `idPagamento`, `idPedidoCliente`),
  INDEX `fk_pagamento_pedido_idx` (`idPagamento` ASC) INVISIBLE,
  INDEX `fk_pedido_entrega_idx` (`idPedido` ASC) VISIBLE,
  INDEX `fk_pedido_cliente_idx` (`idPedidoCliente` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_pedido`
    FOREIGN KEY (`idPagamento`)
    REFERENCES `ecommerce_db`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_entrega`
    FOREIGN KEY (`idPedido`)
    REFERENCES `ecommerce_db`.`Entrega` (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`idPedidoCliente`)
    REFERENCES `ecommerce_db`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Produto_Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Produto_Pedido` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Produto_Pedido` (
  `idProdutoPedido` INT NOT NULL,
  `idPedidoPedido` INT NOT NULL,
  `quantidade` INT NOT NULL DEFAULT 1,
  `statusPedido` ENUM('Disponível', 'Sem estoque') NULL DEFAULT 'Disponível',
  PRIMARY KEY (`idProdutoPedido`, `idPedidoPedido`),
  INDEX `fk_pedido_pedido_idx` (`idPedidoPedido` ASC) VISIBLE,
  CONSTRAINT `fk_produto_pedido`
    FOREIGN KEY (`idProdutoPedido`)
    REFERENCES `ecommerce_db`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_pedido`
    FOREIGN KEY (`idPedidoPedido`)
    REFERENCES `ecommerce_db`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Vendedor` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Vendedor` (
  `idTerceiro` INT NOT NULL AUTO_INCREMENT,
  `razaoSocial` VARCHAR(45) NOT NULL,
  `nomeFantasia` VARCHAR(45) NULL,
  `localidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idTerceiro`),
  UNIQUE INDEX `razaoSocial_UNIQUE` (`razaoSocial` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Estoque` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Estoque` (
  `idEstoqueProduto` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `localidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstoqueProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Fornecedor` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `razaoSocial` VARCHAR(45) NOT NULL,
  `CNPJ` CHAR(15) NOT NULL,
  `contato` CHAR(11) NOT NULL,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Produto_Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Produto_Vendedor` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Produto_Vendedor` (
  `idProdutoVendedor` INT NOT NULL,
  `idProduto` INT NOT NULL,
  `quantidade` INT NULL DEFAULT 1,
  PRIMARY KEY (`idProdutoVendedor`, `idProduto`),
  INDEX `fk_produto_produto_idx` (`idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_produto_vendedor`
    FOREIGN KEY (`idProdutoVendedor`)
    REFERENCES `ecommerce_db`.`Vendedor` (`idTerceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_produto`
    FOREIGN KEY (`idProduto`)
    REFERENCES `ecommerce_db`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Produto_Localidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Produto_Localidade` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Produto_Localidade` (
  `idLocalidadeProduto` INT NOT NULL,
  `idLocalidadeEstoque` INT NOT NULL,
  `localidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLocalidadeProduto`, `idLocalidadeEstoque`),
  INDEX `fk_localidade_estoque_idx` (`idLocalidadeEstoque` ASC) VISIBLE,
  CONSTRAINT `fk_localidade_produto`
    FOREIGN KEY (`idLocalidadeProduto`)
    REFERENCES `ecommerce_db`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_localidade_estoque`
    FOREIGN KEY (`idLocalidadeEstoque`)
    REFERENCES `ecommerce_db`.`Estoque` (`idEstoqueProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Produto_Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Produto_Fornecedor` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Produto_Fornecedor` (
  `idProdutoFornecedorProduto` INT NOT NULL,
  `idProdutoFornecedorEstoque` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idProdutoFornecedorProduto`, `idProdutoFornecedorEstoque`),
  INDEX `fk_produtoFornecedor_estoque_idx` (`idProdutoFornecedorEstoque` ASC) VISIBLE,
  CONSTRAINT `fk_produtoFornecedor_produto`
    FOREIGN KEY (`idProdutoFornecedorProduto`)
    REFERENCES `ecommerce_db`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtoFornecedor_estoque`
    FOREIGN KEY (`idProdutoFornecedorEstoque`)
    REFERENCES `ecommerce_db`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce_db`.`Tipo_Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ecommerce_db`.`Tipo_Cliente` ;

CREATE TABLE IF NOT EXISTS `ecommerce_db`.`Tipo_Cliente` (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('CPF', 'CNPJ') NOT NULL DEFAULT 'CPF',
  `numero` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idTipo`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_tipoCliente`
    FOREIGN KEY (`idTipo`)
    REFERENCES `ecommerce_db`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
